server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loginsystem
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

jwtSecret: jwtSecretKey
jwtExpirationMs: 86400000